apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/app-role
    eks.amazonaws.com/audience: sts.amazonaws.com
    eks.amazonaws.com/token-expiration: "86400"
