AWSTemplateFormatVersion: '2010-09-09'
Description: 'Production EKS Cluster with associated resources'

Parameters:
  ClusterName:
    Type: String
    Default: production-eks
    Description: Name of the EKS cluster

  KubernetesVersion:
    Type: String
    Default: '1.28'
    Description: Kubernetes version for the cluster

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ClusterSecurityGroup
        SubnetIds: 
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      EncryptionConfig:
        - Resources: ['secrets']
          Provider:
            KeyArn: !GetAtt KMSKey.Arn
