apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-spot-cluster
  region: us-west-2
nodeGroups:
  - name: spot-ng
    instanceType: mixed
    minSize: 2
    maxSize: 10
    spot: true
    instanceTypes: ["t3.large", "t3a.large", "m5.large"]
