Resources:
  EKSCostDetector:
    Type: AWS::CE::AnomalyDetector
    Properties:
      Name: eks-cost-anomalies
      MonitorType: DIMENSIONAL
      MonitorDimension: SERVICE
      MonitorSpecification:
        Dimensions:
          - Name: Service
            Value: AmazonEKS
        Tags:
          - Key: Environment
            Values: 
              - Production
      ThresholdExpression:
        Threshold: 100
      AlertSubscriptions:
        - Type: EMAIL
          Address: finance-team@example.com
        - Type: SNS
          TopicArn: !Ref AnomalyAlertTopic
      ReportFrequency: DAILY
