apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: allow-specific-ports
spec:
  podSelector:
    matchLabels:
      role: web
  securityGroups:
    groupIds:
      - sg-123456789
