apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-custom-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: high-performance
  resources:
    requests:
      storage: 100Gi
